import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

interface EmailData {
  to: string;
  subject: string;
  html?: string;
  text?: string;
  from?: string;
}

export default function useEmailService() {
  const [isSending, setIsSending] = useState(false);
  const { toast } = useToast();

  const sendEmail = async (emailData: EmailData) => {
    try {
      setIsSending(true);

      const { data, error } = await supabase.functions.invoke('send-email', {
        body: emailData
      });

      if (error) throw error;

      toast({
        title: "Email Sent! 📧",
        description: "Your email has been sent successfully.",
      });

      return data;
    } catch (error: any) {
      console.error('Email sending error:', error);
      toast({
        title: "Email Error",
        description: error.message,
        variant: "destructive"
      });
      throw error;
    } finally {
      setIsSending(false);
    }
  };

  const sendPostNotification = async (postContent: string, recipientEmail: string) => {
    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="text-align: center; margin-bottom: 30px;">
          <h1 style="color: #0077B5; margin: 0;">LinkedIn Post Generated!</h1>
          <p style="color: #666; margin: 10px 0 0 0;">Your LinkedIn post is ready to publish</p>
        </div>
        
        <div style="background: #f8f9fa; border-radius: 12px; padding: 25px; margin: 25px 0; border-left: 4px solid #0077B5;">
          <h3 style="margin: 0 0 15px 0; color: #333;">Generated Post Content:</h3>
          <div style="background: white; padding: 20px; border-radius: 8px; white-space: pre-wrap; line-height: 1.6; color: #333; border: 1px solid #e1e5e9;">${postContent}</div>
        </div>
        
        <div style="text-align: center; margin: 30px 0;">
          <div style="background: linear-gradient(135deg, #0077B5, #00A0DC); padding: 2px; border-radius: 8px; display: inline-block;">
            <div style="background: white; padding: 20px; border-radius: 6px; margin: 0;">
              <p style="margin: 0; color: #0077B5; font-weight: bold;">🚀 Ready to share with your network!</p>
            </div>
          </div>
        </div>
        
        <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e1e5e9;">
          <p style="margin: 0; color: #666; font-size: 14px;">
            Generated by <strong>LinkedIn Post Generator</strong><br>
            <span style="color: #999;">Create engaging content for your professional network</span>
          </p>
        </div>
      </div>
    `;

    return sendEmail({
      to: recipientEmail,
      subject: "Your LinkedIn Post is Ready! 🚀",
      html: emailHtml,
      text: `Your LinkedIn post is ready!\n\nGenerated Content:\n${postContent}\n\nReady to share with your network!`
    });
  };

  return {
    sendEmail,
    sendPostNotification,
    isSending
  };
}