// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnuxnpjovdzceronqgir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZudXhucGpvdmR6Y2Vyb25xZ2lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTA4NDYsImV4cCI6MjA3MTYyNjg0Nn0.PbIlIO5EI38h35tImO9aLmuRbpolZUz-cW0uFOUVYfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});